default: &default
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  pool:     10
  template: template0
  port: 5432
  password: postgres
  username: postgres

development:
  <<: *default
  database: devtalents_recruitment_task_development

test:
  <<: *default
  database: devtalents_recruitment_task_test

production:
  <<: *default
  database: devtalents_recruitment_task_production